name: Auto Open PR
on:
  push:
    branches-ignore:
      - main
      - master
    tags-ignore:
      - '**'
jobs:
  auto-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fails gracefully if a PR already exists for this branch
          gh pr create --base main --head ${{ github.ref_name }} --fill || true
